version: "3.8"

services:

  mysql:
    image: mysql:8.0
    container_name: ff_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fire-fighter
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: ff_backend
    restart: always
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    container_name: ff_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db_data: